### ISSUE TITLE
Source code could be migrated to "book" repo

### ISSUE THREAD

**Issue by haschdl** [regisfrias/dear-gen-book#9]
I am starting to doubt the initial idea of keeping the source code for the Processing sketches in a separate repository. It could be optional if you wanted to, but having the source code in the book repository simplifies the workflow and puts the whole project "in the same place". 
It feels cumbersome to publish the articles to dear-gen-book and the source to another repository. 
@regisfrias  what do you think?

**Comment by regisfrias** [comment]
I don't know, Daniel Shiffman's Nature of Code has separate repos for the book (https://github.com/shiffman/The-Nature-of-Code) and the  code (https://github.com/shiffman/The-Nature-of-Code-Examples).

What do we gain by having everything in one place?

**Comment by regisfrias** [comment]
Thinking about it now, I think it would make sense to have a separate repo for the code, but we should integrate both our repos.

**Comment by haschdl** [comment]
Agreed! Closed in favour of integrating repos. see issue 
https://github.com/haschdl/dear-gen-code/issues/1
